### ISSUE TITLE
Exception will be encountered when using a JSON that contains `_meta` information

### ISSUE THREAD

**Issue by AdmiralGT** [LectronPusher/botc-custom-script-generator#1]
This block of code is unable to cope with the `_meta` ID which some scripts use to say who the author is

```
for char in script: # preserve character order from the json
	char['id'] = char['id'].replace('_','')
	for role in roles:
		if role['id'] == char['id']:
			char = role
			break
	if char['team'] in char_types:
```

In this case, `char['id']` will resolve to `meta` which then won't match with any roles. You'll then try to access the team key of the meta object which won't exist and will throw an Exception. 

You probably either want to protect against this with `if char.get('team', None) in char_types:` or just a continue block if the `char['id'] == '_meta'`.

**Comment by LectronPusher** [comment]
Thanks for the heads-up, fixed! (and tested with a homebrew script from the discord) I also made a number of improvements to the script so it should stretch properly and be easier to edit the .tex files.
