### ISSUE TITLE
Where do the reminder texts appear?

### ISSUE THREAD

**Issue by quantumpotato** [LectronPusher/botc-custom-script-generator#2]
Where do the reminder texts appear?
I didn't see the reminder texts or marker/token info in the output.

**Comment by LectronPusher** [comment]
Hey, welcome! This is a bit of an old project, but I hope it's helpful.

I don't think I ever added reminder text (or jinxes) to this script. It's designed for half-sheets of letter paper, so there's really not much room for actual text. If you want to try to implement it, you have my blessing (and I'd probably accept a Pull Request), but I'd recommend against writing too much formatting-style LaTeX for your own sanity.

I actually tinkered with converting this to Typst a number of months ago and it seemed quite possible. I may upload that as another repo, but it's much easier to do formatting work in Typst, so if you wanted to implement it, it wouldn't be too hard.

**Comment by quantumpotato** [comment]
Ok, thanks for letting me know. I've ended up just typing a Google docs guide for the storyteller and I think that will be sufficient. I just wanted to make sure I wasn't missing something in the settings.
The project is cool - I'm using it to layout a custom script and it looks nice, thank you for the tool.
